apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
        #  type: NodePort
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
      #      nodePort: 30025
  selector:
    app: jenkins
  externalIPs: ["220.149.13.191"]

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
