apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  labels:
    app.kubernetes.io/managed-by: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins-master
    spec:
      containers:
        - name: jenkins-master
          image: "tolriaz/jenkins-master:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
