apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/managed-by: jenkins
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jenkins
