apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  labels:
    app.kubernetes.io/managed-by: jenkins-jnlp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jenkins
