apiVersion: v1
kind: Service
metadata:
  name: jenkins-slave
  labels:
    app.kubernetes.io/managed-by: jenkins-slave
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jenkins-slave
